version: "3.7"
services:
  vs-code:
    container_name: vs-code
    image: demyx/code-server
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/home/demyx
    environment:
      - CODER_WORKDIR=/root/
      - PASSWORD=password
      - TZ=Africa/Tunis
      - VIRTUAL_HOST=domainname.tld
      - LETSENCRYPT_HOST=domainname.tld
      - LETSENCRYPT_EMAIL=lestencryptemail@gmail.com
      - VIRTUAL_PORT=8080
    user: "0:0"
    network_mode: bridge
